### ISSUE TITLE
Semantic versioning?

### ISSUE THREAD

**Issue by lorenrogers** [eaut/rsync-time-backup#13]
There's a version number in the script, but it doesn't seem to really be used. Perhaps development on this project should follow semantic versioning? If so, it may make sense to track a dev branch too? Something like this http://nvie.com/posts/a-successful-git-branching-model/ ?

**Comment by eaut** [comment]
You are right, the version number is not very useful. I'll probably remove that again. Putting significant effort into that area for such a small script would be overkill.

**Comment by lorenrogers** [comment]
Agreed. Unless there's a need for checking the script version across backups, I don't think we need it.
