### ISSUE TITLE
Ability to change SSH_ARGs

### ISSUE THREAD

**Issue by cgrossde** [eaut/rsync-time-backup#16]
I run my ssh server on a non standard port. It would be nice to influence SSH_ARG with an option. For now I set it manually in line 103: `readonly SSH_ARG="-p1234"`.

I also needed to tell `rsync` to use another port by adding `CMD="$CMD -e \"ssh -p1234\""` after line 408

**Comment by eaut** [comment]
As a first step I have made it simpler to pass special arguments to ssh as well as rsync. Could you verify that editing only line  line 6 of the script in my ["devel" branch](/eaut/rsync-time-backup/tree/devel) is sufficient.

**Comment by cgrossde** [comment]
I get this error when trying to init the remote location: 

```
Bad port '1234 --'
Bad port '1234 --'
Bad port '1234 --'
```

**Comment by eaut** [comment]
I've now added the option --ssh-opt <options>. Should work now.

**Comment by eaut** [comment]
Please reopen this issue if it does not work properly
