### ISSUE TITLE
syntax errors

### ISSUE THREAD

**Issue by danielnovello** [eaut/rsync-time-backup#17]
I get this every time:

daniel:rsync-time-backup daniel$ ./tmbackup.sh init /Users/daniel/Desktop/B 
./tmbackup.sh: line 211: syntax error in conditional expression: unexpected token `('
./tmbackup.sh: line 211: syntax error near`+(['
./tmbackup.sh: line 211: `    if [[ $BACKUP_TS != +([0-9]) ]]; then'

Using a Mac with El Capitan. Any ideas?

**Comment by eaut** [comment]
what is your `bash --version`?

**Comment by eaut** [comment]
Line 211 works fine with bash 4.3.11. OSX El Capitan has a very old bash version 3.2.57. I'll think about a work around.

**Comment by eaut** [comment]
please verify the fix in my devel branch
