### ISSUE TITLE
Pull out default marker logic into separate file

### ISSUE THREAD

**Issue by lorenrogers** [eaut/rsync-time-backup#5]
In order to DRY up some of the script logic, it would probably make sense to use a separate default marker which is copied / read instead of having it hard-coded in the script.

See https://github.com/eaut/rsync-time-backup/pull/2#issuecomment-161599124 for initial discussion.

**Comment by eaut** [comment]
I see no value in a default marker file. Having config files that are needed by the script makes everthing more complicated. The script creates a default config together with a new marker file.
